# Change prefix from 'Ctrl+B' to 'Ctrl+a'
unbind C-a
set -g prefix C-a
bind C-a send-prefix

# Enable mouse mode
set -g mouse on

# Tmux’s default split pane shortcuts, Prefix + % and Prefix + " are not intuitive. 
# | and - are better # symbols to represent vertical and horizontal splits. Why not use them instead?
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# Keeping Current Path
bind c new-window -c "#{pane_current_path}"




